apiVersion: v2
name: retail-store-sample
description: Umbrella chart for AWS retail-store-sample-app (project barakat-2025-capstone)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: retail-store-sample-ui-chart
    alias: ui
    version: ">=0.0.0"
    repository: "file://charts/ui"
    condition: ui.enabled

  - name: retail-store-sample-catalog-chart
    alias: catalog
    version: ">=0.0.0"
    repository: "file://charts/catalog"
    condition: catalog.enabled

  - name: retail-store-sample-cart-chart
    alias: carts
    version: ">=0.0.0"
    repository: "file://charts/carts"
    condition: carts.enabled

  - name: retail-store-sample-checkout-chart
    alias: checkout
    version: ">=0.0.0"
    repository: "file://charts/checkout"
    condition: checkout.enabled

  - name: retail-store-sample-orders-chart
    alias: orders
    version: ">=0.0.0"
    repository: "file://charts/orders"
    condition: orders.enabled

  - name: retail-store-sample-chart
    alias: app
    version: ">=0.0.0"
    repository: "file://charts/app"
    condition: app.enabled
